jobs:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e GH_TOKEN=$GH_TOKEN \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
    else
      yarn release
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

after_success:
  - |
    if [ "$TRAVIS_TAG" == "" ]; then
      TRAVIS_TAG=dev
    fi
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      curl -T dist/bentewee.exe ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
      curl -T dist/bentewee-setup.exe ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
      curl -T dist/bentewee.deb ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
      curl -T dist/bentewee.rpm ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
      curl -T dist/bentewee.tar.gz ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
      curl -T dist/bentewee.AppImage ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
    else
      curl -T dist/bentewee.dmg ${SFTP_ADDRESS}${TRAVIS_TAG}/ --ftp-create-dirs --user ${SFTP_USER}:${SFTP_PASSWORD} --max-time 3600
    fi

branches:
  only:
    - master

notifications:
  email: false
